language: python

python:
  - "3.8"

jobs:
  include:
    - stage: "Build Lab 2."
      name: "Run tests for Lab 2"
      python: 3.8
      install:
        - cd ./ex2/
        - pipenv install
      script: pipenv run pytest tests/tests.py || true
    - stage: "Build Lab 3."
      name: "Run Django Server and test it accessibility. Fail to run and test"
      python: 3.8
      install:
        - cd ./ex3/
        - pipenv install
        - pipenv install requests
        - pipenv install django
      script: bash ./script/travis-build.sh
    
branches:
  only:
    - master
