FROM python:3.8-slim

LABEL author="Arsen"
LABEL version=1.0

# оновлюємо систему
RUN apt-get update && apt-get upgrade -y

# Встановлюємо потрібні пакети
RUN apt-get install git -y && pip install pipenv

# Створюємо робочу папку
WORKDIR /Lab4

# Завантажуємо файли з Git
RUN git clone https://github.com/asiansouldja/matiiash_labs


WORKDIR /App

# Інсталюємо всі залежності
RUN pipenv install

# Відкриваємо порт 8000 на зовні
EXPOSE 8000

# Це команда яка виконається при створенні контейнера
ENTRYPOINT ["pipenv", "run", "python3", "monitoring.py"]
